### ISSUE TITLE
Nutrition config folder doesn't generate

### ISSUE THREAD

**Issue by Darkpixel797** [GTNewHorizons/Nutrition#10]
Upon installing this and its prerequisites, the mod works but only nutrition.cfg is generated in the config folder, the nutrition subfolder where I am supposed to customize it (add nutrient values to foods that don't have it) was not generated.

**Comment by SilearFlare** [comment]
glancing at the code it doesn't seem the file exists to begin with (unlike the upstream verson of nutrition), the values seem to be hardcoded and hand-edited given the last commit.

**Comment by SilearFlare** [comment]
There is a fork that adds the config.
https://github.com/yengman/Nutrition

**Comment by widgetbeck** [comment]
> There is a fork that adds the config. https://github.com/yengman/Nutrition

the "releases" link in the readme appears to just link back to the main fork releases.

**Comment by SilearFlare** [comment]
yeah like a lot of niche forks you're gonna have to compile that one 
good time as any to learn
you can close the issue now by the way
