### ISSUE TITLE
How to add nutrients?

### ISSUE THREAD

**Issue by Goosegit11** [GTNewHorizons/Nutrition#18]
Wiki says to look into nutrition folder but there's no such folder and `nutrition.cfg` is placed into `config/nutrition.cfg` directly

**Comment by serenibyss** [comment]
New nutrient JSONs can be added here: https://github.com/GTNewHorizons/Nutrition/tree/master/src/main/resources/assets/nutrition/configs/nutrients

Currently its not supported to add these via a modpack config folder so you would need to create a repo fork, or JSON loading from the config directory would have to be added
