### ISSUE TITLE
I know how to add nutrition for a food, but how to change the "amount" of this nutrition? 

### ISSUE THREAD

**Issue by iamsoNewBee** [GTNewHorizons/Nutrition#22]
For exsample, every food i added in the "furit" file all provides 1.5% nutrition. How to change the number?

**Comment by serenibyss** [comment]
@iamsoNewBee Nutrition amount is based purely on hunger value. This can be globally tweaked via the "NutritionMultiplier" config.

Additionally if a food has multiple nutrients, nutrient values will be the same for all nutrients, with the amount scaled based on the number of nutrients. This can be tweaked globally via the "LossPerNutrient" config.

To increase an individual food's nutrient values, you would need to increase its hunger value.

**Comment by iamsoNewBee** [comment]
That`s perfect!
